### ISSUE TITLE
Using this library confuses the phone's Apple ID

### ISSUE THREAD

**Issue by jpapillon** [chirag04/react-native-in-app-utils#46]
When I buy a subscription, I'm being asked to enter my iTunes password to make the purchase. Everything goes well and I can buy the subscription. (Except that sometimes I have to enter my password successfully multiple times)

However, things begin to behave strangely on my phone. I'm being asked for my iTunes password all the time. As if something happened that desynchronized my iTunes account with my iPhone.

Has anybody else noticed this behaviour? Thanks!

**Comment by Froelund** [comment]
@jpapillon I have the same issue.

**Comment by adeelraza** [comment]
+1

**Comment by djw27** [comment]
Are you using a test user account rather than your personal apple ID?

**Comment by Froelund** [comment]
@djw27 I'm using my own account, and the products are not published.

**Comment by rohitgoyal** [comment]
+1

**Comment by bbc4468** [comment]
@chirag04 - Can you please help?

**Comment by chirag04** [comment]
I haven't been able to repro this. are you having different icloud account and apple id?

I would have to rely on the community to debug this.

**Comment by chirag04** [comment]
AFAICT, this happens when for some reason the transaction is not cleared from the queue. 

Can somebody confirm if this is happening is release mode also?

My guess is during local dev, a purchase is initiated and you stopped the xcode project. transaction was not cleared from the queue and ios will try to rerun that transaction.

**Comment by jpapillon** [comment]
@chirag04 Might be related to debug/staging builds. I don't hear about that problem with our prod releases.

**Comment by dwilt** [comment]
We're running to this in our projects as well. It doesn't seem to be affecting everyone though.. Scared to push it to production but curious because @jpapillon it saying it's not happening to them in production.

**Comment by chirag04** [comment]
This happens while debugging when the transaction queue is not flushed properly. Manually stopping the Xcode run or crash while debugging can cause this

**Comment by rikur** [comment]
Sorry to continue on a closed issue, but this is still happening. On my TestFlight builds, when purchasing a subscription:

1. I'm asked for my password
2. I'm asked for my password again
3. ..Normal subscription flow begins..
4. I'm asked for my password once more for "TouchID".
5. Subscription flow finishes succesfully.

From then on, I get randomly asked for my password. I know it's for the TestFlight app because it's the only TestFlight app on my phone and the password prompt says [Sandboxed].

This also happens to TestFlight beta-testers, so it doesn't seem to affect only debug builds.

**Comment by dwilt** [comment]
Ok, I think we have figured this out. Basically, if you are running your app through TestFlight and it's not been distributed _through the App Store_, any _non-sandbox iTunes accounts_ will act wonky. We've noticed the multiple passwords being entered as well as purchasing just flat out not working.
