### ISSUE TITLE
restore purchases doesn't work in iOS 10.2.1

### ISSUE THREAD

**Issue by DmytroT** [chirag04/react-native-in-app-utils#75]
restore purchases doesn't work in iOS 10.2.1
it always returns error - restore_failed
I've tried to debug in XCode, the full error message is 'Cannot connect to iTunes Store'

but it worked great with previous ios version (don't remember exactly which one)
it asked for itunes credentials and returned purchases.

in 10.2.1 it stops to ask itunes credentials and always returns this error.

**Comment by juancabraal** [comment]
I have issue with restore too, I'm getting this error message in xcode

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(0x1c46de07 0x1b6d3077 0x1c381e09 0x1c381c73 0x61b113 0x1c376a85 0x277c8dc9 0x277c8841 0xceed67 0xceed53 0xcf35f1 0x1c429a17 0x1c427cff 0x1c377073 0x1c376e81 0x1db1fbfd 0x2151dccf 0x21518401 0x102bc7 0x1bb4250b)
libc++abi.dylib: terminating with uncaught exception of type NSException`

I'm using iPhone 5s 10.0.1(14A403)

**Comment by chirag04** [comment]
`Cannot connect to iTunes Store` could be temporary error? 

Can you confirm restoring purchase on device with ios <10.2 works at the same time when it fails on device with ios >10.2.

**Comment by DmytroT** [comment]
I can confirm that, it worked for me today (unfortunately I forgot to check ios version).
When I've got complains from customers I decided to update ios version (10.2.1). After that it stops working.
I just checked it on 10.2, it doesn't work either.

**Comment by flybayer** [comment]
I'm having this same problem

**Comment by kawashimaken** [comment]
I also have the same issue  as @juancabraal  too, I'm getting this error message in xcode

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(0x18db511b8 0x18c58855c 0x18da34eac 0x18da34d1c 0x100137d2c 0x18da29c18 0x19a7ff66c 0x19a7fef60 0x100421258 0x100421218 0x100426280 0x18dafe810 0x18dafc3fc 0x18da2a2b8 0x18f4de198 0x193a717fc 0x193a6c534 0x10007e49c 0x18ca0d5b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

I'm using iPhone 6 10.2.1(14D27)

**Comment by chirag04** [comment]
Can you put a breakpoint in Xcode and see if originaltransaction is nil?

**Comment by chirag04** [comment]
@kawashimaken can you try with this PR: https://github.com/chirag04/react-native-in-app-utils/pull/78

**Comment by kawashimaken** [comment]
@chirag04 
Thank you for your fast response!
I manually copied your updated file (InAppUtils/InAppUtils.m), after fixed two [:] into [;] in line 131,132 which was suggested by xcode complier, the reported error are gone, and It seems It retrieved all the data it supposed to. I haven't have a thorough check to confirm everything is working at all level, however I just want to let you know that the fix looks good. 👍 

By the way, this may be out of the scope of this library, If I may please allow me to ask
in the following block
```
response.forEach( function(purchase) {
        if (purchase.productIdentifier == "my_app_id") {
          // Handle purchased product.
        }
      });
```
I can retrieve all the purchased product, the next thing I should do is to find the latest one and use its transactionReceipt to validate it, then I know if the user can continue using the app or not, am I right? (Since I am using automatic monthly purchase in my app)

**Comment by chirag04** [comment]
Ok. published a new version on npm with the fix.

about the check, you can keep that check in your apps javascript code.
